version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend/:/usr/src/server'
      - '/usr/src/server/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    networks:
      - jmeteruinetwork
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    links: 
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - jmeteruinetwork
  mongodb:
    # image: mongo
    # restart: always
    container_name: mongodb
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
        - 27017:27017
    # command: mongod --noauth --smallfiles
    networks:
        - jmeteruinetwork
networks: 
  jmeteruinetwork:
    driver: bridge